name: Terraform apply

on: 
    workflow_run:
        workflows: ["Terraform plan"] # Trigger this workflow when the "Terraform plan" workflow completes
        types:
            - completed


jobs:
    Apply:
        if: ${{ github.event.workflow_run.conclusion == 'success' }} # Only run if the plan was successful
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Terraform
              uses: hashicorp/setup-terraform@v2
              with:
                terraform_version: 1.6.6

            - name: configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ secrets.AWS_REGION }}

            - name: Terraform Init
              working-directory: ./terraform
              run: terraform init

            - name: Terraform Apply
              working-directory: ./terraform
              run: terraform apply -auto-approve