name: Terraform plan

on:
  workflow_dispatch:
    inputs:
      confirmation:
        description: type 'plan' to confirm
        required: true
        default: 'no'

jobs:
 # Lint:
  #  name: Tflint 
   # runs-on: ubuntu-latest
    #steps:
#      - name: Checkout code
 #       uses: actions/checkout@v2

#      - name: Abort if Not Confirmed
  #      if: ${{ github.event.inputs.confirmation != 'plan' }}
 #       run: |
 #         echo "Workflow is aborted because you did not say 'plan'."
#          exit 1

   #   - name: Set up Terraform
  #      uses: hashicorp/setup-terraform@v2
 #       with:
#          terraform_version: 1.11.1

#      - name: Install Tflint
 #       run: |
  #        curl -s https://raw.githubusercontent.com/antonbabenko/pre-commit-terraform/master/scripts/install_tflint.sh | bash
   #       echo "Tflint installed successfully"

#      - name: Run Tflint
  #      working-directory: ./terraform
 #       run: tflint --recursive

#  Checkov:
 #   name: Checkov scan
  #  runs-on: ubuntu-latest
   # steps:
    #  - name: Checkout code
     #   uses: actions/checkout@v2

#      - name: Install Checkov
 #       run: |
  #        pip install checkov
#          echo "Checkov installed successfully"

 #     - name: Run Checkov
  #      working-directory: ./terraform
   #     run: |
    #      checkov -d . --quiet
     #     echo "Checkov scan completed successfully"

  #TFsec: 
   # name: Tfsec scan
    #runs-on: ubuntu-latest
    #steps:
     # - name: Checkout code
      #  uses: actions/checkout@v2

#      - name: Install Tfsec
 #       run: |
  #        curl -sSfL https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install.sh | sh
   #       echo "Tfsec installed successfully"
#
 #     - name: Run Tfsec
  #      working-directory: ./terraform
   #     run: tfsec --severity HIGH --soft-fail=false

  TerraformPlan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.11.1

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform fmt
        working-directory: ./terraform
        run: terraform fmt

      - name: Terraform Validate
        working-directory: ./terraform
        run: terraform validate

      - name: Terraform Plan
        working-directory: ./terraform
        run: terraform plan
 